-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2025-05-21 10:38:28 BRT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



DROP TABLE address CASCADE CONSTRAINTS;

DROP TABLE branch CASCADE CONSTRAINTS;

DROP TABLE logs CASCADE CONSTRAINTS;

DROP TABLE motorcycle CASCADE CONSTRAINTS;

DROP TABLE section CASCADE CONSTRAINTS;

DROP TABLE yard CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE address (
    id           RAW(16) NOT NULL,
    street       VARCHAR2(100) NOT NULL,
    "number"     VARCHAR2(7) NOT NULL,
    neighborhood VARCHAR2(100) NOT NULL,
    city         VARCHAR2(100) NOT NULL,
    state        VARCHAR2(100) NOT NULL,
    postal_code  VARCHAR2(20) NOT NULL,
    country      VARCHAR2(50) NOT NULL
);

ALTER TABLE address ADD CONSTRAINT address_pk PRIMARY KEY ( id );

CREATE TABLE branch (
    id         RAW(16) NOT NULL,
    name       VARCHAR2(100) NOT NULL,
    phone      VARCHAR2(20) NOT NULL,
    email      VARCHAR2(100) NOT NULL,
    cnpj       VARCHAR2(14) NOT NULL,
    address_id RAW(16) NOT NULL
);

CREATE UNIQUE INDEX branch__idx ON
    branch (
        address_id
    ASC );

ALTER TABLE branch ADD CONSTRAINT branch_pk PRIMARY KEY ( id );

CREATE TABLE logs (
    id            RAW(16) NOT NULL,
    motorcycle_id RAW(16) NOT NULL,
    mensage       VARCHAR2(150) NOT NULL,
    created_at    DATE NOT NULL
);

ALTER TABLE logs ADD CONSTRAINT logs_pk PRIMARY KEY ( id,
                                                      motorcycle_id );

CREATE TABLE motorcycle (
    id                 RAW(16) NOT NULL,
    model              VARCHAR2(50) NOT NULL,
    engine_type        VARCHAR2(50) NOT NULL,
    plate              CHAR(10) NOT NULL,
    last_revision_date DATE NOT NULL,
    section_id         RAW(16) NOT NULL
);

ALTER TABLE motorcycle ADD CONSTRAINT motorcycle_pk PRIMARY KEY ( id );

CREATE TABLE section (
    id      RAW(16) NOT NULL,
    color   CHAR(50) NOT NULL,
    area    NUMBER(10, 2) NOT NULL,
    yard_id RAW(16) NOT NULL
);

ALTER TABLE section ADD CONSTRAINT section_pk PRIMARY KEY ( id );

CREATE TABLE yard (
    id         RAW(16) NOT NULL,
    branch_id  RAW(16) NOT NULL,
    name       VARCHAR2(100) NOT NULL,
    address_id RAW(16) NOT NULL,
    area       NUMBER(10, 2) NOT NULL
);

CREATE UNIQUE INDEX yard__idx ON
    yard (
        address_id
    ASC );

ALTER TABLE yard ADD CONSTRAINT yard_pk PRIMARY KEY ( id );

ALTER TABLE branch
    ADD CONSTRAINT branch_address_fk FOREIGN KEY ( address_id )
        REFERENCES address ( id );

ALTER TABLE logs
    ADD CONSTRAINT logs_motorcycle_fk FOREIGN KEY ( motorcycle_id )
        REFERENCES motorcycle ( id );

ALTER TABLE motorcycle
    ADD CONSTRAINT motorcycle_section_fk FOREIGN KEY ( section_id )
        REFERENCES section ( id );

ALTER TABLE section
    ADD CONSTRAINT section_yard_fk FOREIGN KEY ( yard_id )
        REFERENCES yard ( id );

ALTER TABLE yard
    ADD CONSTRAINT yard_address_fk FOREIGN KEY ( address_id )
        REFERENCES address ( id );

ALTER TABLE yard
    ADD CONSTRAINT yard_branch_fk FOREIGN KEY ( branch_id )
        REFERENCES branch ( id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             6
-- CREATE INDEX                             2
-- ALTER TABLE                             12
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
